repo_token: amaY2x5UeOYks2mcBsUq6LK6Eo5dyly65
language: python
python:
  - "3.8"
install:
  - pip install -r requirements.txt
  - pip install -r requirements_dev.txt
  - pip install coveralls
script:
  - pytest --cov=src/
after_success:
  - coveralls

